### ISSUE TITLE
Kml coma bug and additional questions.

### ISSUE THREAD

**Issue by k4ven** [Bullhill/agf-converter#1]
Hi, thanks for your tool, because of it I was able to reproduce some functionnalities in Python. When using the attached AgData file, the coordinates in the kml uses coma instead of dot, which make the kml invalid. It may be a behaviour related to my french Windows install. You'll also find guidance lines in the AgData file, which should be the same as the isoxmlfile. If you want to visualize the isoxml, https://newholland.myplmconnect.com/ is an option. If you still wish so, I may be able to provide example files with different geometries. Strangely, the polygons seems to be of type 2 in the file ( 0 == Point, 1 == Line, 3 == Polygon, 4 == MultiPolygon). 
![Nature_MyPLMConnect](https://github.com/Bullhill/agf-converter/assets/49309841/5bfcf4e6-04c3-4f9e-9ce3-69ecffd9c8de)
[example_files.zip](https://github.com/Bullhill/agf-converter/files/14692484/example_files.zip)

**Comment by Bullhill** [comment]
Sorry late answer. have fixed your issue in V0.03
